# my-composite-action/action.yml
name: "My Composite Action"
description: "A composite action that performs multiple steps"
inputs:
  input1:
    description: "First input"
    required: true
  input2:
    description: "Second input"
    required: true
runs:
  using: "composite"
  steps:
      
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        shell: bash
        run: pytest
      - name: Print input1
        shell: bash
        run: echo "Input1 is  ${{ inputs.input1 }}"

      - name: Print input2
        shell: bash
        run: echo "Input2 is ${{ inputs.input2 }}"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the Node.js version
          cache: 'yarn'      # Cache Yarn dependencies for faster builds

      - name: Install Yarn
        run: npm install -g yarn
        shell: bash

      - name: Install dependencies
        run: yarn install
        shell: bash

      - name: Build project
        run: yarn build
        shell: bash

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
    

